<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variabel”**

**Disusun Oleh :**

**Fajri Ramadhan**

**2611533006**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png.jpeg" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Saya menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Dalam pemrograman, data merupakan salah satu komponen penting yang digunakan untuk menjalankan suatu program. Setiap data yang digunakan dalam program memiliki jenis atau tipe tertentu. Tipe data berfungsi untuk menentukan jenis nilai yang dapat disimpan dan bagaimana data tersebut diproses oleh komputer.

Selain tipe data, variabel juga merupakan bagian penting dalam pemrograman. Variabel digunakan sebagai tempat untuk menyimpan data yang nilainya dapat digunakan dan diubah selama program berjalan. Dengan memahami tipe data dan variabel, seseorang dapat membuat program yang lebih terstruktur, efektif, dan mudah dipahami.

Oleh karena itu, praktikum mengenai tipe data dan variabel dilakukan agar mahasiswa dapat memahami konsep dasar penyimpanan data dalam program serta mampu menerapkannya dalam pembuatan program sederhana.

## 1.2 Tujuan
1. Memahami pengertian tipe data dalam pemrograman.
2. Mengetahui berbagai macam tipe data.
3. Memahami pengertian dan fungsi variabel.
4. Mengetahui cara mendeklarasikan dan menggunakan variabel.
5. Mampu menerapkan tipe data dan variabel dalam program sederhana.

## 1.3 Manfaat
1. Penguasaan Fondasi Pemrograman
2. Peningkatan Keterampilan Praktis (Hands-On)
3. Pencegahan Kesalahan Logika Kode

---
# BAB II
# PEMBAHASAN

## 2.1 Landasan Teori

**1. Pengenalan Bahasa Pemrograman Python**

Python merupakan salah satu bahasa pemrograman tingkat tinggi yang menggunakan konsep interpreted, object-oriented, dan dynamically typed. Python pertama kali dikembangkan oleh Guido van Rossum pada tahun 1991. Bahasa ini dirancang dengan sintaks yang sederhana dan mudah dibaca, sehingga cukup banyak digunakan untuk pembelajaran maupun pengembangan program. Python dapat diterapkan dalam berbagai bidang, seperti pembuatan perangkat lunak, otomatisasi, analisis data, dan kecerdasan buatan.

​**2. Konsep Variabel dalam Python**

Variabel digunakan untuk menyimpan sebuah nilai yang nantinya dapat digunakan kembali dalam program. Pada Python, variabel dapat dibuat secara langsung dengan memberikan nilai menggunakan tanda = tanpa harus menentukan tipe datanya terlebih dahulu. Dalam penulisannya, nama variabel memiliki beberapa aturan, seperti membedakan huruf besar dan kecil (case-sensitive), tidak boleh diawali angka, serta tidak dapat menggunakan kata kunci yang sudah digunakan oleh Python.

**​3. Tipe Data Dasar**

Tipe data menunjukkan jenis nilai yang disimpan dalam sebuah variabel. Python memiliki beberapa tipe data dasar yang sering digunakan, yaitu:

-Integer (int): digunakan untuk menyimpan bilangan bulat, seperti -5, 0, dan 100.

-Float (float): digunakan untuk menyimpan bilangan yang memiliki nilai desimal, seperti 3.14 dan -0.01.

-String (str): digunakan untuk menyimpan teks atau kumpulan karakter yang ditulis menggunakan tanda petik, seperti "Praktikum Python".

-Boolean (bool): digunakan untuk menyimpan nilai logika yang terdiri dari True dan False.

**​4. Dynamic Typing dan Type Casting**

Python menggunakan sistem dynamic typing, yaitu tipe data variabel dapat ditentukan secara otomatis berdasarkan nilai yang diberikan ketika program dijalankan. Python juga menyediakan type casting yang digunakan untuk mengubah suatu nilai dari satu tipe data ke tipe lainnya. Contohnya adalah penggunaan int(), float(), dan str(). Pemahaman mengenai type casting diperlukan agar data dapat digunakan sesuai dengan operasi yang dilakukan dan mengurangi kemungkinan terjadinya type error.

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611533006"

In [4]:
# Buat file dengan nama Boolean_NIM.py
# Nama variable ditambah 4 digit nim terakhir contoh: nilai_1234
# Deklarasi variabel dengan tipe data Boolean
is_lulus_3006 = True
is_cumlaude_3006 = True

# Menggunakan Boolean
nilai_3006 = 85
batas_lulus_3006 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_3006 = nilai_3006 >= batas_lulus_3006 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_3006)
print("Apakah Lulus?:", status_kelulusan_3006)
if is_lulus_3006 and is_cumlaude_3006:
    print("Selamat, Anda lulus dengan predikat Cum Laude!")

=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cum Laude!


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_3006 dengan nilai True dan is_cumlaide_3006 dengan nilai False.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
4. Bagian 6 sampai 8 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan ke layar.

### 2.2.2 Program "Input_2611533006"

In [3]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama Variabel ditambah 4 digit terakhir nim contoh: panjang_1234
# Program ini menggunakan fungi Input() umtuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_3006 = input('Masukkan nilai panjang: ')
lebar_3006 = input('Masukkan nilai lebar: ')
luas_3006 = int(panjang_3006) * int(lebar_3006)
print("Luas =", luas_3006)

Luas = 375


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Bagian 3 berfungsi untuk mengubah nilai panjang dan lebar menjadi tipe data integer, kemudian menghitung luas persegi panjang.
3. Bagian 4 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke layar.

### 2.2.3 Program "Konstanta_2611533006"

In [4]:
# Buat file dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit terakhir nim contoh: jari_1234

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_3006 = float(input('Masukkan nilai jari-jari: '))
luas_3006 = PI * jari_3006 * jari_3006
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3006, luas_3006))

pi: 3.140000
Luas lingkaran dengan jari-jari 14.00 adalah 615.44


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk mengimpor Final dan menentukan nilai konstanta PI sebesar 3.14.
2. Bagian 3 sampai 4 berfungsi untuk menampilkan nilai PI dan meminta pengguna memasukkan nilai jari-jari lingkaran.
3. Bagian 5 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
4. Bagian 6 berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.4 Program "Numerik_2611533006"

In [7]:
# Buat file dengan nama Numerik_NIM.py
# nama variable ditambah 4 digit terakhir NIM contoh: a_5500
#create a variable with integer value.
a_3006=100
print("The type of variable having value", a_3006, " is ", type(a_3006))

#create a variable with float value
b_3006=10.2345
print("The type of variable having value", b_3006, " is ", type(b_3006))

#create a variable with complex value.
c_3006=100+3j
print("The type of variable having value", c_3006, " is ", type(c_3006))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_3006 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type().
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_3006 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_3006 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya.

### 2.2.5 Program "String_2611533006"

In [6]:
# Buat file dengan nama String_NIM.py
#nama variable ditambah 4 digit NIM terakhir contoh: nama_1234
#ganti programnya dan data masing2
nama_3006 = "Fajri Ramadhan"
jenis_kelamin_3006 = ' L '
alamat_3006 = """
    Jl. Kubu Bawah no 45
    kec. Mandiangin Koto Selayan
    kota Bukittinggi
"""
agama_3006 = 'Islam'
print("Nama saya adalah: ", nama_3006)
print("Jenis kelamin saya adalah: ", jenis_kelamin_3006)
print("Alamat saya addlah: ", alamat_3006)
print("Agama saya adalah: ", agama_3006)

Nama saya adalah:  Fajri Ramadhan
Jenis kelamin saya adalah:   L 
Alamat saya addlah:  
    Jl. Kubu Bawah no 45
    kec. Mandiangin Koto Selayan
    kota Bukittinggi

Agama saya adalah:  Islam


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_3006 dan jenis_kelamin_3006 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_3006 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_3006 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa tipe data merupakan jenis data yang menentukan bentuk nilai yang dapat disimpan oleh suatu variabel. Beberapa tipe data dasar yang digunakan antara lain integer, float, char, string, dan boolean.

Variabel berfungsi sebagai tempat untuk menyimpan data dalam program. Setiap variabel harus memiliki tipe data dan nama yang sesuai. Pemahaman mengenai tipe data dan variabel merupakan dasar yang sangat penting dalam pemrograman karena hampir seluruh program menggunakan keduanya untuk mengolah dan menyimpan informasi.

---
## DAFTAR PUSTAKA

[1]  ​Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly Media. Link: https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[2] ​Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (2nd ed.). No Starch Press. Link: https://nostarch.com/pythoncrashcourse2e

[3] ​Severance, C. R. (2016). Python for Everybody: Exploring Data in Python 3. CreateSpace Independent Publishing Platform. Link: https://www.py4e.com/book

[4] ​Swaroop, C. H. (2013). A Byte of Python. Link: https://python.swaroopch.com/